scope: postgres-cluster

restapi:
  listen: 0.0.0.0:8008
  connect_address: "{{ .Env.NAME }}:8008"

etcd3:
  hosts: etcd:2379
  protocol: http

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        wal_keep_segments: 64
        max_wal_senders: 10
        max_replication_slots: 10

postgresql:
  listen: 0.0.0.0:5432
  connect_address: "{{ .Env.NAME }}:5432"
  data_dir: /var/lib/postgresql/data
  bin_dir: /usr/lib/postgresql/16/bin
  authentication:
    replication:
      username: repl_user
      password: repl_password
    superuser:
      username: postgres
      password: admin_password