global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'predict-server'
    static_configs:
      - targets: ['predict-server:5002']

  - job_name: 'simulator'
    static_configs:
      - targets: ['simulator:8000','simulator:8000','simulator:8000']
      
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'postgres-master-exporter'
    static_configs:
      - targets: ['postgres-exporter-master:9187']
  - job_name: 'postgres-replica-exporter'
    static_configs:
      - targets: ['postgres-exporter-replica:9187']
  - job_name: 'patroni'
    static_configs:
      - targets: ['postgres-master:8008', 'postgres-replica:8008']